"""Add reset code to user

Revision ID: 048b80fd4109
Revises: 16daf4faf4ac
Create Date: 2025-12-11 03:04:30.996795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048b80fd4109'
down_revision = '16daf4faf4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiration')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
