"""Add preferred_time to Subscription

Revision ID: 16daf4faf4ac
Revises: 37e3b8ea5f45
Create Date: 2025-11-28 03:53:50.563280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16daf4faf4ac'
down_revision = '37e3b8ea5f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_time', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('preferred_time')

    # ### end Alembic commands ###
