"""Add loyalty_points_threshold to SiteSettings

Revision ID: 314539bbf99f
Revises: 34718154f33d
Create Date: 2025-12-11 06:05:50.402049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314539bbf99f'
down_revision = '34718154f33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('loyalty_points_threshold')

    # ### end Alembic commands ###
