"""Add latitude and longitude to neighborhood

Revision ID: 318556405b7e
Revises: a3b0dfe383b9
Create Date: 2026-03-23 10:21:58.565880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318556405b7e'
down_revision = 'a3b0dfe383b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'service_size_price' in inspector.get_table_names():
        op.drop_table('service_size_price')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('booking_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('service_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('size_price_adjustment',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_item_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('city_service_price', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_unique_constraint('unique_city_service_size', ['city_id', 'service_id', 'vehicle_size_id'])

    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('city_service_price', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_service_size', type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('booking_item', schema=None) as batch_op:
        batch_op.alter_column('total_item_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('size_price_adjustment',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('service_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    op.create_table('service_size_price',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_size_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['vehicle_size_id'], ['vehicle_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
