"""Add payment_method to booking

Revision ID: 34718154f33d
Revises: e4d12f11c607
Create Date: 2025-12-11 05:44:37.872840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34718154f33d'
down_revision = 'e4d12f11c607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
