"""Add VehicleSize model and update Vehicle/Booking

Revision ID: 37e3b8ea5f45
Revises: a83e24308ac1
Create Date: 2025-11-23 23:44:43.726441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e3b8ea5f45'
down_revision = 'a83e24308ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'vehicle_size' not in tables:
        op.create_table('vehicle_size',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name_ar', sa.String(length=64), nullable=True),
        sa.Column('name_en', sa.String(length=64), nullable=True),
        sa.Column('price_adjustment', sa.Float(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    with op.batch_alter_table('booking', schema=None) as batch_op:
        columns = [c['name'] for c in inspector.get_columns('booking')]
        if 'vehicle_size_price' not in columns:
            batch_op.add_column(sa.Column('vehicle_size_price', sa.Float(), nullable=True))
        if 'discount_amount' in columns:
            batch_op.drop_column('discount_amount')

    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('valid_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('valid_until',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_index('ix_discount_code_code')
        batch_op.create_unique_constraint('uq_discount_code_code', ['code'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        columns = [c['name'] for c in inspector.get_columns('vehicle')]
        if 'vehicle_size_id' not in columns:
            batch_op.add_column(sa.Column('vehicle_size_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_vehicle_vehicle_size_id', 'vehicle_size', ['vehicle_size_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicle_vehicle_size_id', type_='foreignkey')
        batch_op.drop_column('vehicle_size_id')

    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.drop_constraint('uq_discount_code_code', type_='unique')
        batch_op.create_index('ix_discount_code_code', ['code'], unique=False)
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.drop_column('vehicle_size_price')

    op.drop_table('vehicle_size')
    # ### end Alembic commands ###
