"""add push subscription

Revision ID: 46bbfd3595a7
Revises: e49b4f6c399e
Create Date: 2025-11-21 14:47:09.668582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bbfd3595a7'
down_revision = 'e49b4f6c399e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_subscription_vehicle_id', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('push_subscription', sa.Text(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
