"""Add booking days limit settings

Revision ID: 47651ea2ea37
Revises: 6febcd58693b
Create Date: 2026-02-19 02:02:59.679547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47651ea2ea37'
down_revision = '6febcd58693b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_days_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_days_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('subscription_days_limit')
        batch_op.drop_column('booking_days_limit')

    # ### end Alembic commands ###
