"""Add subscription fields

Revision ID: 6b7569268cda
Revises: c0e506d501ec
Create Date: 2025-11-20 21:16:39.718925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7569268cda'
down_revision = 'c0e506d501ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subscription_neighborhood_id', 'neighborhood', ['neighborhood_id'], ['id'])
        batch_op.create_foreign_key('fk_subscription_employee_id', 'user', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_employee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscription_neighborhood_id', type_='foreignkey')
        batch_op.drop_column('neighborhood_id')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
