"""Add shift_number to EmployeeSchedule

Revision ID: 6febcd58693b
Revises: 2fed7f610de0
Create Date: 2026-01-16 04:07:29.099995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6febcd58693b'
down_revision = '2fed7f610de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_schedule', schema=None) as batch_op:
        batch_op.drop_column('shift_number')

    # ### end Alembic commands ###
