"""Add rating fields to Booking

Revision ID: 713f03d82abe
Revises: 048b80fd4109
Create Date: 2025-12-11 03:46:28.000226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713f03d82abe'
down_revision = '048b80fd4109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('rating_date')
        batch_op.drop_column('rating_comment')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
