"""add boundary_coords to neighborhood

Revision ID: 7c235d73fb9d
Revises: a8276f51fcb5
Create Date: 2026-03-22 02:31:06.320840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c235d73fb9d'
down_revision = 'a8276f51fcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'city_product_price' not in tables:
        op.create_table('city_product_price',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('city_id', sa.Integer(), nullable=False),
            sa.Column('product_id', sa.Integer(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('city_id', 'product_id', name='unique_city_product')
        )
    else:
        with op.batch_alter_table('city_product_price', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
            batch_op.create_unique_constraint('unique_city_product', ['city_id', 'product_id'])

    if 'city_service_price' not in tables:
        op.create_table('city_service_price',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('city_id', sa.Integer(), nullable=False),
            sa.Column('service_id', sa.Integer(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
            sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('city_id', 'service_id', name='unique_city_service')
        )
    else:
        with op.batch_alter_table('city_service_price', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
            batch_op.create_unique_constraint('unique_city_service', ['city_id', 'service_id'])

    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('boundary_coords', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.drop_column('boundary_coords')

    with op.batch_alter_table('city_service_price', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_service', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('city_product_price', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_product', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
