"""Add SubscriptionPackage model

Revision ID: 96b73199e66e
Revises: 4a1b8d5f8e8e
Create Date: 2025-11-20 15:59:34.004305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b73199e66e'
down_revision = '4a1b8d5f8e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=64), nullable=True),
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('wash_count', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subscription_package_id', 'subscription_package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_package_id', type_='foreignkey')
        batch_op.drop_column('package_id')

    op.drop_table('subscription_package')
    # ### end Alembic commands ###
