"""Add CityPackagePrice model

Revision ID: a3b0dfe383b9
Revises: 7c235d73fb9d
Create Date: 2026-03-22 11:28:50.185186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b0dfe383b9'
down_revision = '7c235d73fb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'city_package_price' not in tables:
        op.create_table('city_package_price',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('city_id', sa.Integer(), nullable=False),
            sa.Column('package_id', sa.Integer(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
            sa.ForeignKeyConstraint(['package_id'], ['subscription_package.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('city_id', 'package_id', name='unique_city_package')
        )
        
    with op.batch_alter_table('referral_record', schema=None) as batch_op:
        # Check if referral_record table exists before altering
        if 'referral_record' in tables:
            batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('city_package_price')
    # ### end Alembic commands ###
