"""add allow_free_washes to season

Revision ID: a8276f51fcb5
Revises: 11f58fcbaa2d
Create Date: 2026-03-11 04:18:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8276f51fcb5'
down_revision = '11f58fcbaa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_free_washes', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('allow_free_washes')
    # ### end Alembic commands ###
