"""Add SiteSettings model

Revision ID: e28520235d7c
Revises: 6b7569268cda
Create Date: 2025-11-20 23:49:26.256758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28520235d7c'
down_revision = '6b7569268cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('instagram_url', sa.String(length=200), nullable=True),
    sa.Column('terms_content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_subscription_neighborhood_id', 'neighborhood', ['neighborhood_id'], ['id'])
        batch_op.create_foreign_key('fk_subscription_employee_id', 'user', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_employee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscription_neighborhood_id', type_='foreignkey')

    op.drop_table('site_settings')
    # ### end Alembic commands ###
