"""Add mawthooq_url to site_settings

Revision ID: e4d12f11c607
Revises: 713f03d82abe
Create Date: 2025-12-11 05:02:33.566408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d12f11c607'
down_revision = '713f03d82abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mawthooq_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('mawthooq_url')

    # ### end Alembic commands ###
