"""Add PushSubscription

Revision ID: f865f3df0a98
Revises: e28520235d7c
Create Date: 2025-11-21 00:16:04.226247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f865f3df0a98'
down_revision = 'e28520235d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_subscription_neighborhood_id', 'neighborhood', ['neighborhood_id'], ['id'])
        batch_op.create_foreign_key('fk_subscription_employee_id', 'user', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_employee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscription_neighborhood_id', type_='foreignkey')

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
